# Site settings
author: Emily Miles
title: Emily Miles, Web Developer in Training
header-img: img/home-bg.png
email: emiles4@gmail.com
copyright_name: Emily Miles
description: > # this means to ignore newlines until "baseurl:"
  Always learning, growing, adapting
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  emiles4

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
